// Lightweight, dependency-free tests for the zhuyin engine core. Run via
// ctest or by invoking the built zhuyin_engine_tests binary directly.
#include "zhuyin/engine.h"

#include <cstdio>
#include <cstdlib>
#include <string>

namespace {
int g_failures = 0;

void Check(bool condition, const char* expr, const char* file, int line) {
  if (!condition) {
    std::fprintf(stderr, "FAIL: %s (%s:%d)\n", expr, file, line);
    ++g_failures;
  }
}
}  // namespace

#define CHECK(expr) Check((expr), #expr, __FILE__, __LINE__)
#define CHECK_EQ(a, b)                                                   \
  Check((a) == (b), #a " == " #b, __FILE__, __LINE__)

using zhuyin::BopomofoKeyboard;
using zhuyin::Candidate;
using zhuyin::Decoder;
using zhuyin::Dictionary;
using zhuyin::SyllableComposer;

void TestKeyboardMapping() {
  CHECK_EQ(BopomofoKeyboard::KeyToSymbol('1'), std::string("ㄅ"));
  CHECK_EQ(BopomofoKeyboard::KeyToSymbol('y'), std::string("ㄗ"));
  CHECK_EQ(BopomofoKeyboard::KeyToSymbol('9'), std::string("ㄞ"));
  CHECK_EQ(BopomofoKeyboard::KeyToSymbol('4'), std::string("ˋ"));
  CHECK_EQ(BopomofoKeyboard::KeyToSymbol('u'), std::string("ㄧ"));
  CHECK_EQ(BopomofoKeyboard::KeyToSymbol('~'), std::string());  // unmapped
  CHECK(BopomofoKeyboard::IsInitialSymbol("ㄗ"));
  CHECK(BopomofoKeyboard::IsMedialSymbol("ㄧ"));
  CHECK(BopomofoKeyboard::IsToneSymbol("ˋ"));
}

void TestSyllableComposerBasicSyllable() {
  // ㄗㄞˋ ("zai4", 在/再): initial ㄗ, final ㄞ, tone ˋ.
  SyllableComposer c;
  CHECK(c.Empty());
  CHECK(c.AddSymbol("ㄗ") == SyllableComposer::AddResult::kAdded);
  // ㄗ is itself a standalone-capable initial (it can be the whole syllable
  // "zi"), so HasFinal() is already true here; adding ㄞ below extends it
  // to "zai" instead.
  CHECK(c.HasFinal());
  CHECK(c.AddSymbol("ㄞ") == SyllableComposer::AddResult::kAdded);
  CHECK(c.HasFinal());
  CHECK(c.AddSymbol("ˋ") == SyllableComposer::AddResult::kAdded);
  CHECK_EQ(c.Reading(), std::string("ㄗㄞˋ"));
  CHECK(c.BackspaceSymbol());
  CHECK_EQ(c.Reading(), std::string("ㄗㄞ"));
}

void TestSyllableComposerStandaloneInitial() {
  // ㄕˋ ("shi4", 是): initial ㄕ alone is already a complete syllable.
  SyllableComposer c;
  CHECK(c.AddSymbol("ㄕ") == SyllableComposer::AddResult::kAdded);
  CHECK(c.HasFinal());  // standalone-capable initial
  CHECK(c.AddSymbol("ˋ") == SyllableComposer::AddResult::kAdded);
  CHECK_EQ(c.Reading(), std::string("ㄕˋ"));
}

void TestSyllableComposerRejectsToneWithoutVowel() {
  SyllableComposer c;
  CHECK(c.AddSymbol("ㄆ") == SyllableComposer::AddResult::kAdded);  // ㄆ alone
  // ㄆ is not standalone-capable, so a tone cannot be added yet.
  CHECK(c.AddSymbol("ˋ") == SyllableComposer::AddResult::kRejected);
}

#ifndef ZHUYIN_DICTIONARY_PATH
#define ZHUYIN_DICTIONARY_PATH "data/dictionary.tsv"
#endif

const char* kSampleDictionary =
    "在\tㄗㄞˋ\t149249\n"
    "再\tㄗㄞˋ\t18287\n"
    "我\tㄨㄛˇ\t500000\n"
    "這\tㄓㄜˋ\t100000\n"
    "裡\tㄌㄧˇ\t80000\n"
    "一\tㄧ\t400000\n"
    "次\tㄘˋ\t50000\n"
    "在這裡\tㄗㄞˋ ㄓㄜˋ ㄌㄧˇ\t511\n"
    "再一次\tㄗㄞˋ ㄧ ㄘˋ\t102\n"
    "我在\tㄨㄛˇ ㄗㄞˋ\t1037\n"
    "我再\tㄨㄛˇ ㄗㄞˋ\t195\n"
    "這裡\tㄓㄜˋ ㄌㄧˇ\t2000\n";

void TestDictionaryParsesFixtureAndRanksByWeight() {
  // This fixture intentionally has an unrealistic (tiny, hand-picked)
  // weight distribution, so it is only used to check that parsing/grouping/
  // sorting works, NOT to check real-corpus segmentation behavior (that
  // needs the full generated dictionary -- see the tests below).
  Dictionary dict;
  CHECK(dict.LoadFromString(kSampleDictionary));
  CHECK(dict.EntryCount() > 0);
  std::vector<std::string> syllables = {"ㄗㄞˋ"};
  const auto* matches = dict.Lookup(syllables, 0, 1);
  CHECK(matches != nullptr);
  CHECK(matches->size() >= 2);
  CHECK_EQ((*matches)[0].text, std::string("在"));  // higher weight first
}

void TestDecoderPrefersReAgainOverZaiInLongerPhrase() {
  // Typed syllables for "再一次" (zai4 yi2 ci4 / zai4 yi1 ci4): ㄗㄞˋ ㄧ ㄘˋ.
  // Uses the full, real-corpus-frequency dictionary generated by
  // tools/build_dictionary.py: realistic frequency proportions (not a
  // hand-picked toy fixture) are what make the language-model decoder
  // correctly prefer the compound "再一次" over spelling it out character
  // by character.
  Dictionary dict;
  if (!dict.LoadFromFile(ZHUYIN_DICTIONARY_PATH)) {
    std::fprintf(stderr,
                  "SKIP: could not load %s -- run "
                  "tools/build_dictionary.py first\n",
                  ZHUYIN_DICTIONARY_PATH);
    return;
  }
  Decoder decoder(dict);

  std::vector<std::string> syllables = {"ㄗㄞˋ", "ㄧ", "ㄘˋ"};
  std::vector<Candidate> sentence = decoder.ComposeBestSentence(syllables);

  std::string joined;
  for (const auto& c : sentence) joined += c.text;
  CHECK_EQ(joined, std::string("再一次"));
}

void TestDecoderPrefersZaiHereOverReHere() {
  // Typed syllables for "我在這裡": ㄨㄛˇ ㄗㄞˋ ㄓㄜˋ ㄌㄧˇ.
  Dictionary dict;
  if (!dict.LoadFromFile(ZHUYIN_DICTIONARY_PATH)) {
    std::fprintf(stderr,
                  "SKIP: could not load %s -- run "
                  "tools/build_dictionary.py first\n",
                  ZHUYIN_DICTIONARY_PATH);
    return;
  }
  Decoder decoder(dict);

  std::vector<std::string> syllables = {"ㄨㄛˇ", "ㄗㄞˋ", "ㄓㄜˋ", "ㄌㄧˇ"};
  std::vector<Candidate> sentence = decoder.ComposeBestSentence(syllables);

  std::string joined;
  for (const auto& c : sentence) joined += c.text;
  CHECK_EQ(joined, std::string("我在這裡"));
  // Must never resolve to the homophone-confused "我再這裡".
  CHECK(joined.find("再") == std::string::npos);
}

void TestGetCandidatesAtOffersBothHomophones() {
  Dictionary dict;
  CHECK(dict.LoadFromString(kSampleDictionary));
  Decoder decoder(dict);

  std::vector<std::string> syllables = {"ㄗㄞˋ"};
  std::vector<Candidate> candidates = decoder.GetCandidatesAt(syllables, 0);
  CHECK(candidates.size() >= 2);
  // 在 (weight 149249) must outrank 再 (weight 18287) for the bare syllable.
  CHECK_EQ(candidates[0].text, std::string("在"));
}

int main() {
  TestKeyboardMapping();
  TestSyllableComposerBasicSyllable();
  TestSyllableComposerStandaloneInitial();
  TestSyllableComposerRejectsToneWithoutVowel();
  TestDictionaryParsesFixtureAndRanksByWeight();
  TestDecoderPrefersReAgainOverZaiInLongerPhrase();
  TestDecoderPrefersZaiHereOverReHere();
  TestGetCandidatesAtOffersBothHomophones();

  if (g_failures == 0) {
    std::printf("All tests passed.\n");
    return 0;
  }
  std::fprintf(stderr, "%d test(s) failed.\n", g_failures);
  return 1;
}
